template-file-path: templates/root.yaml

parameters:
  ProjectName: ecs-cicd
  TemplatesBucketUrl: REPLACE_WITH_TemplatesBucketUrl_FROM_BOOTSTRAP_OUTPUTS
  InitialImageUri: REPLACE_WITH_INITIAL_ECR_IMAGE_URI
  GitHubConnectionArn: REPLACE_WITH_CODECONNECTIONS_ARN
  InfraRepoOwner: mahorobonheur
  InfraRepoName: ecs-cicd-infra
  InfraRepoBranch: main
  GitHubOwner: mahorobonheur
  AppRepoName: ecs-cicd-app

tags:
  Project: ecs-cicd
  Environment: production
  ManagedBy: CloudFormation-GitSync
