template-file-path: templates/root.yaml

parameters:
  ProjectName: ecs-cicd
  TemplatesBucketUrl: '{{resolve:ssm:/ecs-cicd/templates-bucket-url}}'
  InitialImageUri: public.ecr.aws/nginx/nginx:stable-alpine
  GitHubConnectionArn: '{{resolve:ssm:/ecs-cicd/github-connection-arn}}'
  InfraRepoOwner: mahorobonheur
  InfraRepoName: ecs-cicd-infra
  InfraRepoBranch: main
  GitHubOwner: mahorobonheur
  AppRepoName: ecs-cicd-app

tags:
  Project: ecs-cicd
  Environment: production
  ManagedBy: CloudFormation-GitSync
